import type { Metadata } from "next";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { HelpCircle } from "lucide-react";

export const metadata: Metadata = {
  title: "FAQ - Frequently Asked Questions | AI-Learn Platform",
  description: "Find answers to common questions about AI-Learn Platform. Learn how to create AI-powered courses, upload PDFs, track progress, and more.",
  openGraph: {
    title: "FAQ - AI-Learn Platform",
    description: "Frequently asked questions about AI-powered course generation and learning",
  },
};

export default function FAQPage() {
  const faqs = [
    {
      category: "Getting Started",
      questions: [
        {
          q: "What is AI-Learn Platform?",
          a: "AI-Learn Platform is an AI-powered educational tool that transforms any text, PDF, or document into a structured, interactive learning experience. Upload your materials and get a complete course with lessons, quizzes, and video resources in under 60 seconds."
        },
        {
          q: "How do I create my first course?",
          a: "Simply upload a PDF or paste text on the homepage. Specify your desired course duration (15-60 minutes), and our AI will analyze the content and generate a comprehensive course with modules, lessons, quizzes, and relevant video resources."
        },
        {
          q: "Do I need to create an account?",
          a: "You can try the platform without an account, but creating a free account allows you to save your progress, track completed courses, earn certificates, and access your courses from any device."
        },
        {
          q: "Is AI-Learn free to use?",
          a: "Yes! We offer a free tier that allows you to create and study courses. Premium features may be available in the future for advanced users."
        }
      ]
    },
    {
      category: "Course Generation",
      questions: [
        {
          q: "What types of content can I upload?",
          a: "You can upload PDFs, paste text directly, or provide documents on topics like technology, science, business, history, languages, and more. Our AI works best with educational or informational content."
        },
        {
          q: "How long does it take to generate a course?",
          a: "Most courses are generated in 30-60 seconds. The AI analyzes your content, structures it into modules and lessons, generates quizzes, and finds relevant video resources automatically."
        },
        {
          q: "Can I customize the course duration?",
          a: "Yes! When creating a course, you can specify your desired learning time (15, 30, 45, or 60 minutes). The AI will structure the content to fit your time constraints."
        },
        {
          q: "What AI models do you use?",
          a: "We primarily use DeepSeek for course generation, with support for Google Gemini and Ollama. These models analyze your content, extract key concepts, generate quizzes, and find appropriate learning resources."
        },
        {
          q: "How accurate is the AI-generated content?",
          a: "Our AI is trained on extensive educational data and includes validation steps. However, we recommend reviewing the content, especially for critical topics. Each course includes an AI audit report highlighting strengths and areas for improvement."
        }
      ]
    },
    {
      category: "Learning Experience",
      questions: [
        {
          q: "How are courses structured?",
          a: "Courses are divided into modules, each containing multiple lessons. Every lesson includes key concepts, explanations, interactive quizzes, and supplementary resources like YouTube videos and articles."
        },
        {
          q: "Can I track my progress?",
          a: "Yes! The platform automatically tracks which lessons you've completed, quiz scores, and overall course progress. Your progress is saved to your account and syncs across devices."
        },
        {
          q: "What are the quizzes like?",
          a: "Each lesson includes multiple-choice quizzes with 3-5 questions designed to reinforce key concepts. Questions are automatically generated by AI based on the lesson content."
        },
        {
          q: "How do YouTube videos work?",
          a: "Our AI automatically finds relevant educational YouTube videos for each lesson. Videos are validated to ensure they're accessible and appropriate. You can watch them directly in the lesson interface."
        },
        {
          q: "Can I take notes while learning?",
          a: "Yes! Each lesson includes a notes and drawing panel where you can write notes, sketch diagrams, and save your thoughts for later review."
        }
      ]
    },
    {
      category: "Certificates & Achievements",
      questions: [
        {
          q: "Can I earn certificates?",
          a: "Yes! Upon completing a course, you'll earn a certificate of completion that includes the course title, completion date, and your name. Certificates can be downloaded as PDFs."
        },
        {
          q: "What are achievements?",
          a: "Achievements are milestones you unlock by completing courses, maintaining learning streaks, and reaching study goals. They're tracked in your profile and saved to your account."
        },
        {
          q: "How do I access my certificates?",
          a: "Completed course certificates are available in your dashboard's certificate gallery. You can view, download, or share them at any time."
        }
      ]
    },
    {
      category: "Technical Questions",
      questions: [
        {
          q: "What browsers are supported?",
          a: "AI-Learn works best on modern browsers like Chrome, Firefox, Safari, and Edge. We recommend using the latest version for the best experience."
        },
        {
          q: "Can I use AI-Learn on mobile devices?",
          a: "Yes! Our platform is fully responsive and works on smartphones and tablets. However, for the best experience with note-taking and drawing features, we recommend using a tablet or desktop."
        },
        {
          q: "Is my data secure?",
          a: "Yes. We use Firebase Authentication and Supabase for secure data storage. Your documents and progress are encrypted and only accessible to you. We don't share your data with third parties."
        },
        {
          q: "Can I delete my account and data?",
          a: "Yes, you can delete your account and all associated data at any time from your account settings. This action is permanent and cannot be undone."
        }
      ]
    },
    {
      category: "Troubleshooting",
      questions: [
        {
          q: "The AI couldn't generate a course from my PDF. What should I do?",
          a: "Try these solutions: 1) Ensure your PDF contains readable text (not just images), 2) Check that the content is educational or informational, 3) Try a shorter document first, 4) Make sure the PDF isn't password-protected or corrupted."
        },
        {
          q: "Video resources aren't loading. How do I fix this?",
          a: "Our system automatically validates YouTube links. If videos aren't loading: 1) Check your internet connection, 2) Try refreshing the page, 3) Some videos may be region-restricted. The system will attempt to find alternatives."
        },
        {
          q: "My progress isn't saving. What's wrong?",
          a: "Make sure you're logged in to your account. Progress tracking requires authentication. If you're logged in and still having issues, try clearing your browser cache and logging in again."
        },
        {
          q: "I'm getting an error when uploading a PDF. Help!",
          a: "Check that: 1) Your PDF is under 10MB, 2) The file isn't corrupted, 3) You have a stable internet connection. If issues persist, try converting your PDF to text and pasting it directly instead."
        }
      ]
    }
  ];

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="text-center mb-12">
        <HelpCircle className="w-16 h-16 mx-auto mb-4 text-primary" />
        <h1 className="text-4xl md:text-5xl font-bold mb-4">
          Frequently Asked Questions
        </h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Find answers to common questions about AI-Learn Platform and how to get the most out of AI-powered learning.
        </p>
      </div>

      <div className="space-y-8">
        {faqs.map((category, idx) => (
          <Card key={idx}>
            <CardHeader>
              <CardTitle className="text-2xl">{category.category}</CardTitle>
              <CardDescription>
                {category.questions.length} questions
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {category.questions.map((faq, qIdx) => (
                  <AccordionItem key={qIdx} value={`${idx}-${qIdx}`}>
                    <AccordionTrigger className="text-left">
                      {faq.q}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.a}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Contact section */}
      <Card className="mt-12 bg-primary/5">
        <CardHeader>
          <CardTitle>Still Have Questions?</CardTitle>
          <CardDescription>
            Can't find what you're looking for? We're here to help!
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <p>Contact us at: <a href="mailto:support@your-domain.com" className="text-primary hover:underline font-semibold">support@your-domain.com</a></p>
          <p>Join our community: <a href="#" className="text-primary hover:underline font-semibold">Discord Server</a></p>
          <p>Follow updates: <a href="#" className="text-primary hover:underline font-semibold">Twitter @AILearnPlatform</a></p>
        </CardContent>
      </Card>

      {/* Structured data for FAQPage */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": faqs.flatMap(category => 
              category.questions.map(faq => ({
                "@type": "Question",
                "name": faq.q,
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": faq.a
                }
              }))
            )
          })
        }}
      />
    </div>
  );
}
